### ISSUE TITLE
About Training Corpus

### ISSUE THREAD

**Issue by Yeom** [BLLIP/bllip-parser#29]
trainParser -parser [data directory] [training corpus] [development corpus]

1) if i train the training data i need 2 corpus training corpus and development corpus
but i don't know what is development corpus well.

2) In the [data directory], there must be featInfo.*,bugFix.txt, headInfo.txt, terms.txt, (and training corpus, dev corpus)?

3) Can i add my training data(parsing model) result to original training data(parsing model)?

**Comment by dmcc** [comment]
Can you give a description of what kind of parsing model you're trying to train? (what type of training data do you have? what language?)

1) In general, the development corpus is usually a portion (5-20%) of the overall training data which is not used for training. This allows the parser to better adjust some of the smoothing parameters to handle unseen data. For example, when training Wall Street Journal parsers, usually about 20 sections are used for training and 1 section is used for development.

2) That's mostly right -- the featInfo.*, bugFix.txt (which can be empty), terms.txt, and headInfo.txt files are parameters for the parsing model and should be in the new model directory. Training and development corpora shouldn't be in it. If you're not changing languages/treebanks, you can safely copy an existing data directory to make a new one since the training script will overwrite the other files in it (this is in the TRAIN README.rst -- please read it). If you're training a parser for a new language, you will probably want to adjust them -- there's some discussion about this in issue #22.

3) Unfortunately, you can't easily combine parsing models given their complicated file formats and since each has its own index which you'd need to remap. The easiest way is usually to combine the training the training corpora and then make a model from that.

**Comment by Yeom** [comment]
I'm really thank you for answering my weird question TT
